### ISSUE TITLE
Git error on run from source

### ISSUE THREAD

**Issue by RyanPaiva56** [pyarmak/Laracasts-Downloader#1]
I get this error:

laracasts-downloader.go:5:2: cannot find package "github.com/PuerkitoBio/goquery" in any of:
    /usr/src/pkg/github.com/PuerkitoBio/goquery (from $GOROOT)
    ($GOPATH not set)
laracasts-downloader.go:6:2: cannot find package "github.com/cheggaaa/pb" in any of:
    /usr/src/pkg/github.com/cheggaaa/pb (from $GOROOT)
    ($GOPATH not set)

Any ideas?

Thanks!

**Comment by pyarmak** [comment]
You need to set your go environment variables.
See http://golang.org/cmd/go/#hdr-GOPATH_environment_variable for more detail.
